stages:
  data_ingestion:
    cmd: python src/cnnClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/cnnClassifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Chest-CT-Scan-data

  training:
    cmd: python src/cnnClassifier/pipeline/stage_02_model_trainer.py
    deps:
      - src/cnnClassifier/pipeline/stage_02_model_trainer.py
      - config/config.yaml
      - artifacts/data_ingestion/Chest-CT-Scan-data
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
      - HYPERPARAMETERS.learning_rate.min
      - HYPERPARAMETERS.learning_rate.max
      - HYPERPARAMETERS.learning_rate.sampling
      - HYPERPARAMETERS.freeze_till.min
      - HYPERPARAMETERS.freeze_till.max
      - HYPERPARAMETERS.freeze_till.step
      - HYPERPARAMETERS.dense_units.min
      - HYPERPARAMETERS.dense_units.max
      - HYPERPARAMETERS.dense_units.step
      - TUNER.max_trials
      - TUNER.executions_per_trial      
    outs:
      - artifacts/training/model.h5


  evaluation:
    cmd: python src/cnnClassifier/pipeline/stage_03_model_evaluation.py
    deps:
      - src/cnnClassifier/pipeline/stage_03_model_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/Chest-CT-Scan-data
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false